version: "3.3"


services:

  billing:
    build:
      dockerfile: ./images/backend/prod/Dockerfile
      context: .
    image: billing_prod
    volumes:
    - type: bind
      source: ./src
      target: /srv/billing/src
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5007:5007"
      - "8000:8000"
    entrypoint: /srv/billing/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

volumes:
  db_data: